### ISSUE TITLE
Sparse file support breaks pipe output on decompression.

### ISSUE THREAD

**Issue by eborisch** [Cyan4973/lz4#110] opened 2015-05-22 15:15 UTC
On FreeBSD; 'liblz4-129'; installed via portmaster.

This used to work, but fails with 129:
```
cat /dev/urandom | lz4c | lz4c -d | cat > /dev/null
Error 68 : Skip error (sparse file)
```

I can make the piped output version work again with --no-sparse on the decompression step; i.e. both of these work:
```
cat /dev/urandom | lz4c | lz4c -d --no-sparse | cat > /dev/null
cat /dev/urandom | lz4c | lz4c -d > /dev/null
```

It seems to me that --no-sparse should be the default when outputting to a pipe; and to be compatible with other (bzip2, gzip, etc) filters that don't require an additional flag. This could be accomplished either via stat() and S_ISREG() testing, or by gracefully recovering on a skip error. (My guess is the former will be more straightforward to implement, and the latter a more robust solution for unexpected cases.)

**Comment by t-mat** [comment] 2015-05-22 15:48
Hi, @eborisch.  Thanks for the report !

Recently, we have same reports

 - #105 : Disabled sparse file mode when output file is terminal.
 - [Sparse file by default is breaking pipelines](https://groups.google.com/forum/#!msg/lz4c/YGS4bE9f3-M/P_G7SuI5nXoJ) @ LZ4c

And it has been resolved by 60d657a.

So, could you try [latest dev branch](https://github.com/Cyan4973/lz4/tree/dev) ?
The following command will work on BSD platforms:

```
cd
mkdir my-lz4 && cd my-lz4
git clone -b dev https://github.com/Cyan4973/lz4.git .
cd programs
make lz4c
# Or use "gmake" :
# gmake lz4c
cat /dev/urandom | ./lz4c | ./lz4c -d | cat > /dev/null
```

**Comment by t-mat** [comment] 2015-05-22 16:02
note : xz has interesting comment for sparse file mode
"[Creating a sparse file is not possible when O_APPEND is active](http://git.tukaani.org/?p=xz.git;a=blob;f=src/xz/file_io.c;h=e5a29925d97645718a87f82b55903324595ddf6c;hb=c7f4041f6b8f4729f88d3bc888b2a4080ae51f72#l883)".

**Comment by eborisch** [comment] 2015-05-22 16:08
So sorry for the duplicate -- I thought I had searched, but clearly I missed it.

Confirmed that latest dev branch works as advertised on FreeBSD 10.1. Closing. Thanks for the excellent SW & quick response! I'll contact the FreeBSD port maintainer to make sure they are aware. Any chance of a new tagged release with this fix?

**Comment by t-mat** [comment] 2015-05-22 17:10
No problem :smile:  I also need more smart search for issues on github.  Anyway, thanks for confirming !
For new release, since three consecutive issues are unusual for this project, I'm asking @Cyan4973 for now.

**Comment by Cyan4973** [comment] 2015-05-23 13:26
Thanks for reporting.
The current patch in "dev" branch works well enough for `lz4cat` situations,
unfortunately, the new test case reported by @t-mat, using `>>` redirector,
would silently fail.
Getting around this problem seems to require some OS-specific libraries.

I'm therefore inclined on selecting the stronger option to disable sparse support on `stdout`.

For your comments

**Comment by ido** [comment] 2015-05-23 14:31
FWIW, selfishly, I'd prefer if you kept/fixed sparse support on all output types on OSes that support it well if you can.  Or, at the very least, on Linux...  :-/

**Comment by Cyan4973** [comment] 2015-05-23 17:54
The short term proposal
would be to have "_default_ sparse support disabled on `stdout`"
but it could still be enabled by using `--sparse` command, which overrides defaults settings.

Default sparse support would remain enabled for direct write-to-file operations, which don't suffer above issues.

Is that nonetheless a problem for you @ido ?

**Comment by eborisch** [comment] 2015-05-23 19:25
Seems like a reasonable approach. The associated error message could also call out the fix. "Try --no-sparse."

Corner cases (named pipe passed as output file argument?) likely still exist. To be truly robust, but still support sparse files, perhaps the seek on the output stream should be attempted and then gracefully handled (by disabling sparse) on EPIPE / SIGPIPE. Likely only needs to be tested at start of execution; perhaps during argument parsing.

**Comment by Cyan4973** [comment] 2015-05-23 19:49
> perhaps the seek on the output stream should be attempted and then gracefully handled (by disabling sparse)

This is how it is currently handled within "dev" branch.
The problem is, with `>>` redirection, `fseek()` pretends that everything works properly, so there is no way to catch the problem.
The `>>` redirection issue, related to append mode, is only possible when using `stdout`.

> The associated error message could also call out the fix. "Try --no-sparse."

Good point !

**Comment by Cyan4973** [comment] 2015-05-25 06:56
Latest update in "dev" branch acae59a73969f436f95ed31130efe0ee9f7b3e48
fixes `>>` redirection issue (and already reported console & cat issues)
by disabling sparse mode by default on stdout.
It's still possible to force it using `--sparse`.

One of the last remaining questions is : should it be made a hotfix (due to `lz4cat` being currently broken), or can it wait for a future r130 ?

**Comment by t-mat** [comment] 2015-05-25 20:03
:+1: for hotfix !

**Comment by Cyan4973** [comment] 2015-05-29 18:21
Moved to master

**Closed by Cyan4973** 2015-05-29 18:21 UTC
