### ISSUE TITLE
Real time compression

### ISSUE THREAD

**Issue by djazoi** [Cyan4973/lz4#168] opened 2015-11-27 08:56 UTC
Hi,

I am reading data in real time and trying to compress it using 'LZ4_compress_fast_continue' function. For that I was refereeing, 'examples/blockStreaming_doubleBuffer.c' from lz4-r131. But it is not compressing properly and I am not able to regenerate the data.

In my case, block size is of 448 bytes.

Can you please help me?

Thanks.

**Comment by Cyan4973** [comment] 2015-11-27 10:03
`blockStreaming_doubleBuffer.c` is known to perform properly, it is re-tested at every build.
So I guess you changed something to it in your implementation, which would be logical.

But without more details, it will be difficult to help.

**Comment by djazoi** [comment] 2015-11-27 10:06
Hi @Cyan4973,

Thanks for your quick response.

I am not saying that  blockStreaming_doubleBuffer.c  is not working properly. I was saying that I am taking reference of  blockStreaming_doubleBuffer.c file to use compression function defined in 'lz4.c'. But it data is not compressed properly.

Thanks.

**Comment by Cyan4973** [comment] 2015-11-27 10:29
Understood. Though it still doesn't describe what you are doing.

**Comment by djazoi** [comment] 2015-11-27 10:56
Let me explain what I am doing:

1. Two global variables:
        LZ4_stream_t lz4Stream_body;
        LZ4_stream_t* lz4Stream = &lz4Stream_body;

2. After that first, Resetting the stream:
        LZ4_resetStream(lz4Stream);

3. Then at every 64ms I am reading data of 448bytes and giving it to the compression function:

        #define BLOCK_BYTES  448

        char* const inpPtr = (char *) readBuffer; // Typecast 'readBuffer' before assigning it to character pointer 'inpPtr' because it is array of unsigned short.

        char cmpBuf[LZ4_COMPRESSBOUND(BLOCK_BYTES)];

        const int cmpBytes = LZ4_compress_fast_continue(lz4Stream, inpPtr, 
                                                        cmpBuf, BLOCK_BYTES,
                                                        sizeof(cmpBuf), 1);

4. Then first send 'cmpBytes' and then 'cmpBuf' over the network.

5. Repeat steps 1-4 for around 10-15 seconds.

**Comment by Cyan4973** [comment] 2015-11-27 11:11
Your approach looks clean. It can work properly, but non described minor details could also get in the way :

- inpPtr value is not described. If it is the same value at each call, then the previous buffer content has been overwritten. In which case, `LZ4_compress_fast_continue()` should detect it, and simply not use it during compression. Compression ratio will be worse, but that's all. It should still work.

- `LZ4_compress_fast_continue()` only compress blocks, but doesn't generate any header. Consequently, if you want to decompress the generated block, you'll need to provide necessary information to the decoder (`LZ4_decompress_safe_continue()` typically). It includes the size of the compressed block, and the maximum possible size to regenerate (which you know, it is `BLOCK_BYTES`).


Regards

**Comment by djazoi** [comment] 2015-11-27 11:49
Hi,

I am using two 448 bytes of buffer in alternate fashion to read the data and assigning it to the inpPtr. So I hope that would be fine!

Yes, I have modified the double buffer example code to just decompress the compressed file, but doesn't work as the file was not compressed properly.

Should I use any other method, other than ' LZ4_compress_fast_continue()' to compress data in real time?

Thanks.

**Comment by Cyan4973** [comment] 2015-11-27 12:00
Each call to ` LZ4_compress_fast_continue()` generates a full compressed block.
It's not a "single file", it's a serie of blocks.
You need header information in front of each one of them.

**Comment by djazoi** [comment] 2015-11-27 12:05
That is fine.. But the file generated after compression is of same size as the file without compression.. So there was not compression at all.. and even I was not able to decompress the file using ' LZ4_decompress_safe_continue() '.

**Comment by Cyan4973** [comment] 2015-11-27 12:07
Difficult to say. Maybe your source data cannot be compressed.
I guess it is necessary to study a working sample. a gist of something like that.

**Comment by djazoi** [comment] 2015-11-27 12:12
Data is compressible, as the uncompressed file contains same data can be compressed with double buffer example!!

Can you suggest any working example that I can refer?

**Comment by Cyan4973** [comment] 2015-11-27 12:15
If the double buffer example works, then something is probably wrong in your implementation.
But there is no way to tell without reading it.

**Comment by djazoi** [comment] 2015-11-27 13:09
I am using the lz4.c and lz4.h file as it is. Not a single line of code change. And I also explained the application level implementation, which is also good enough. So I am not able to understand what is the problem!! Why is it not compressing the data?

**Comment by woodstock23** [comment] 2015-11-27 14:03
djazoi, every experienced programmer knows that it is not good enough to explain the application level implementation. There could be side effects that you can't imagine. I just had a very difficult case of data injection recently which caused a problem in an unrelated part.
So just believe Cyan if he says that there is no way to tell without reading it or maybe even to debug it. You asked for a working example, but you already have blockStreaming_doubleBuffer.c. So now it it is up to you to provide a non-working example. Otherwise you can't expect more help than you have already received.
Cyan, by the way, many thanks for your good work! I am one of many happy developers who uses lz4 successfully.

**Comment by Cyan4973** [comment] 2015-11-30 00:25
Thanks for the kind words @woodstock23.

Since no new element were provided, I guess I will close this point.

**Closed** 2015-11-30 00:25 UTC

**Comment by djazoi** [comment] 2015-11-30 07:37
@Cyan4973, @woodstock23,

Thanks for your support.

By 'Good Enough, I mean that the implementation I have done at application side to use lz4 was good enough as said by @Cyan4973. There is nothing much other than that in my code.

I am using it on the embedded platform, not on PC! Does this make any difference?

Thanks.

**Comment by woodstock23** [comment] 2015-11-30 07:52
Every platform can introduce different kinds of effects, just think of all the issues with endianess. But lz4 supports many kinds of platforms, so it should not make a difference.
The bottom line stays the same: There is no obvious reason so far why it doesn't work.

**Comment by Cyan4973** [comment] 2015-11-30 09:59
I still believe the issue is likely in the metadata handling.
But sadly, there is no way to tell from the sample, since no metadata is described.
No read / write operation is present either.

**Comment by djazoi** [comment] 2015-11-30 10:53
Hi @Cyan4973 ,

As I said, I am reading 448 bytes of data and give it to function 'LZ4_compress_fast_continue' to compress it. Then I am sending the 'cmpBytes' and 'cmpBuf' over the network to the connected client. Client is receiving the data and just dumping it to the file. 

At the end when I am seeing the size of the file, there is no change. It was same as the uncompressed data file, though it is not same as uncompressed file!!

Can you please explain, which metadata you are talking about?

Thanks.

**Comment by Cyan4973** [comment] 2015-11-30 11:10
> Can you please explain, which metadata you are talking about?

`cmpBytes` in your described use case.

>  Client is receiving the data and just dumping it to the file. At the end when I am seeing the size of the file, there is no change. It was same as the uncompressed data file, 

If the compressed file is *exactly* the same size as original one, you are possibly making a mistake during file dumping, such as writing the nb of original bytes instead of the nb of compressed bytes.

This kind of mistake could be more confidently diagnosed by looking at the code directly. 
A summarized verbal description of the program logic cannot provide the level of details required for an investigation. Programming is unforgiving, a small typing or logic mistake can have far reaching consequences. Unfortunately, very small details matter, and they do not transpire through verbal descriptions.
